export const AZNAR_RECICLADOS_FABRICS = [
  {
    "id": "aznar-reciclados-caribe-coiba-060",
    "name": "Coiba 060",
    "family": "Aznar Caribe",
    "color": "#9E9F9C",
    "swatch": "/images/fabrics/aznar-reciclados/caribe-coiba-060.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=693c281d9c791_1765550109&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Caribe",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-caribe-nassau-060",
    "name": "Nassau 060",
    "family": "Aznar Caribe",
    "color": "#B2B3AF",
    "swatch": "/images/fabrics/aznar-reciclados/caribe-nassau-060.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=693c281d9c791_1765550109&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Caribe",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-caribe-martinica-060",
    "name": "Martinica 060",
    "family": "Aznar Caribe",
    "color": "#ACADA9",
    "swatch": "/images/fabrics/aznar-reciclados/caribe-martinica-060.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=693c281d9c791_1765550109&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Caribe",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-caribe-abaco-060",
    "name": "Abaco 060",
    "family": "Aznar Caribe",
    "color": "#A9ABA8",
    "swatch": "/images/fabrics/aznar-reciclados/caribe-abaco-060.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=693c281d9c791_1765550109&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Caribe",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-caribe-habana-060",
    "name": "Habana 060",
    "family": "Aznar Caribe",
    "color": "#BABBB7",
    "swatch": "/images/fabrics/aznar-reciclados/caribe-habana-060.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=693c281d9c791_1765550109&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Caribe",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-caribe-caicos-060",
    "name": "Caicos 060",
    "family": "Aznar Caribe",
    "color": "#C7C8C3",
    "swatch": "/images/fabrics/aznar-reciclados/caribe-caicos-060.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=693c281d9c791_1765550109&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Caribe",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-caribe-basico-000",
    "name": "Basico 000",
    "family": "Aznar Caribe",
    "color": "#F0ECDF",
    "swatch": "/images/fabrics/aznar-reciclados/caribe-basico-000.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=693c281d9c791_1765550109&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Caribe",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-caribe-caicos-061",
    "name": "Caicos 061",
    "family": "Aznar Caribe",
    "color": "#B4ADA2",
    "swatch": "/images/fabrics/aznar-reciclados/caribe-caicos-061.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=693c2f2f7f167_1765551919&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Caribe",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-caribe-abaco-061",
    "name": "Abaco 061",
    "family": "Aznar Caribe",
    "color": "#C0B8AB",
    "swatch": "/images/fabrics/aznar-reciclados/caribe-abaco-061.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=693c2f2f7f167_1765551919&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Caribe",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-caribe-nassau-061",
    "name": "Nassau 061",
    "family": "Aznar Caribe",
    "color": "#C3BBB0",
    "swatch": "/images/fabrics/aznar-reciclados/caribe-nassau-061.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=693c2f2f7f167_1765551919&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Caribe",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-caribe-coiba-061",
    "name": "Coiba 061",
    "family": "Aznar Caribe",
    "color": "#C5BDB2",
    "swatch": "/images/fabrics/aznar-reciclados/caribe-coiba-061.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=693c2f2f7f167_1765551919&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Caribe",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-adriana-006",
    "name": "Adriana 006",
    "family": "Aznar Domus",
    "color": "#B2B5B3",
    "swatch": "/images/fabrics/aznar-reciclados/domus-adriana-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-adriana-030",
    "name": "Adriana 030",
    "family": "Aznar Domus",
    "color": "#EFEEE1",
    "swatch": "/images/fabrics/aznar-reciclados/domus-adriana-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-diana-006",
    "name": "Diana 006",
    "family": "Aznar Domus",
    "color": "#BBBDBF",
    "swatch": "/images/fabrics/aznar-reciclados/domus-diana-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-diana-030",
    "name": "Diana 030",
    "family": "Aznar Domus",
    "color": "#C9C5BB",
    "swatch": "/images/fabrics/aznar-reciclados/domus-diana-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-fannia-006",
    "name": "Fannia 006",
    "family": "Aznar Domus",
    "color": "#B1B3B5",
    "swatch": "/images/fabrics/aznar-reciclados/domus-fannia-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-fannia-030",
    "name": "Fannia 030",
    "family": "Aznar Domus",
    "color": "#D3CFC4",
    "swatch": "/images/fabrics/aznar-reciclados/domus-fannia-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-hora-006",
    "name": "Hora 006",
    "family": "Aznar Domus",
    "color": "#B6B8B7",
    "swatch": "/images/fabrics/aznar-reciclados/domus-hora-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-hora-030",
    "name": "Hora 030",
    "family": "Aznar Domus",
    "color": "#EFEDE2",
    "swatch": "/images/fabrics/aznar-reciclados/domus-hora-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-iris-006",
    "name": "Iris 006",
    "family": "Aznar Domus",
    "color": "#AFB1B0",
    "swatch": "/images/fabrics/aznar-reciclados/domus-iris-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-iris-030",
    "name": "Iris 030",
    "family": "Aznar Domus",
    "color": "#ECEADE",
    "swatch": "/images/fabrics/aznar-reciclados/domus-iris-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-juno-006",
    "name": "Juno 006",
    "family": "Aznar Domus",
    "color": "#B5B7B7",
    "swatch": "/images/fabrics/aznar-reciclados/domus-juno-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-juno-030",
    "name": "Juno 030",
    "family": "Aznar Domus",
    "color": "#ECEBE0",
    "swatch": "/images/fabrics/aznar-reciclados/domus-juno-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-malena-006",
    "name": "Malena 006",
    "family": "Aznar Domus",
    "color": "#B6B8B7",
    "swatch": "/images/fabrics/aznar-reciclados/domus-malena-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-malena-030",
    "name": "Malena 030",
    "family": "Aznar Domus",
    "color": "#EEECE1",
    "swatch": "/images/fabrics/aznar-reciclados/domus-malena-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-marcia-006",
    "name": "Marcia 006",
    "family": "Aznar Domus",
    "color": "#B2B4B6",
    "swatch": "/images/fabrics/aznar-reciclados/domus-marcia-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-marcia-030",
    "name": "Marcia 030",
    "family": "Aznar Domus",
    "color": "#C9C5BB",
    "swatch": "/images/fabrics/aznar-reciclados/domus-marcia-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-tulia-006",
    "name": "Tulia 006",
    "family": "Aznar Domus",
    "color": "#BFC1C2",
    "swatch": "/images/fabrics/aznar-reciclados/domus-tulia-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-tulia-030",
    "name": "Tulia 030",
    "family": "Aznar Domus",
    "color": "#C9C5BB",
    "swatch": "/images/fabrics/aznar-reciclados/domus-tulia-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-velia-006",
    "name": "Velia 006",
    "family": "Aznar Domus",
    "color": "#C0C2C4",
    "swatch": "/images/fabrics/aznar-reciclados/domus-velia-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-velia-030",
    "name": "Velia 030",
    "family": "Aznar Domus",
    "color": "#C9C5BB",
    "swatch": "/images/fabrics/aznar-reciclados/domus-velia-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-seya-006",
    "name": "Seya 006",
    "family": "Aznar Domus",
    "color": "#B0B2B4",
    "swatch": "/images/fabrics/aznar-reciclados/domus-seya-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694141cd4c561_1765884365&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-seya-030",
    "name": "Seya 030",
    "family": "Aznar Domus",
    "color": "#D4D0C5",
    "swatch": "/images/fabrics/aznar-reciclados/domus-seya-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694141cd4c561_1765884365&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-elia-006",
    "name": "Elia 006",
    "family": "Aznar Domus",
    "color": "#B4B6B7",
    "swatch": "/images/fabrics/aznar-reciclados/domus-elia-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69414797b051d_1765885847&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-elia-030",
    "name": "Elia 030",
    "family": "Aznar Domus",
    "color": "#D5D0C5",
    "swatch": "/images/fabrics/aznar-reciclados/domus-elia-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69414797b051d_1765885847&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-helena-006",
    "name": "Helena 006",
    "family": "Aznar Domus",
    "color": "#B6B7BA",
    "swatch": "/images/fabrics/aznar-reciclados/domus-helena-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69415478d2c97_1765889144&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-domus-helena-030",
    "name": "Helena 030",
    "family": "Aznar Domus",
    "color": "#D6D0C5",
    "swatch": "/images/fabrics/aznar-reciclados/domus-helena-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69415478d2c97_1765889144&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-whitte-eco-lambert-000",
    "name": "Lambert 000",
    "family": "Aznar Whitte Eco",
    "color": "#E7E4E7",
    "swatch": "/images/fabrics/aznar-reciclados/whitte-eco-lambert-000.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69419443b1d96_1765905475&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Whitte Eco",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-whitte-eco-lambert-005",
    "name": "Lambert 005",
    "family": "Aznar Whitte Eco",
    "color": "#C2C2C2",
    "swatch": "/images/fabrics/aznar-reciclados/whitte-eco-lambert-005.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69419443b1d96_1765905475&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Whitte Eco",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-whitte-eco-lambert-006",
    "name": "Lambert 006",
    "family": "Aznar Whitte Eco",
    "color": "#B0ACB1",
    "swatch": "/images/fabrics/aznar-reciclados/whitte-eco-lambert-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69419443b1d96_1765905475&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Whitte Eco",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-whitte-eco-lambert-008",
    "name": "Lambert 008",
    "family": "Aznar Whitte Eco",
    "color": "#938F93",
    "swatch": "/images/fabrics/aznar-reciclados/whitte-eco-lambert-008.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69419443b1d96_1765905475&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Whitte Eco",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-whitte-eco-lambert-009",
    "name": "Lambert 009",
    "family": "Aznar Whitte Eco",
    "color": "#747074",
    "swatch": "/images/fabrics/aznar-reciclados/whitte-eco-lambert-009.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69419443b1d96_1765905475&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Whitte Eco",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-whitte-eco-lambert-062",
    "name": "Lambert 062",
    "family": "Aznar Whitte Eco",
    "color": "#CFCAC0",
    "swatch": "/images/fabrics/aznar-reciclados/whitte-eco-lambert-062.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69419443b1d96_1765905475&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Whitte Eco",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-whitte-eco-lambert-063",
    "name": "Lambert 063",
    "family": "Aznar Whitte Eco",
    "color": "#BCB1A9",
    "swatch": "/images/fabrics/aznar-reciclados/whitte-eco-lambert-063.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69419443b1d96_1765905475&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Whitte Eco",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-whitte-eco-lambert-065",
    "name": "Lambert 065",
    "family": "Aznar Whitte Eco",
    "color": "#9A918B",
    "swatch": "/images/fabrics/aznar-reciclados/whitte-eco-lambert-065.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69419443b1d96_1765905475&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Whitte Eco",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-casablanca-anfa-061",
    "name": "Anfa 061",
    "family": "Aznar Casablanca",
    "color": "#BDB5A1",
    "swatch": "/images/fabrics/aznar-reciclados/casablanca-anfa-061.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=6942cec98baf6_1765985993&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Casablanca",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  },
  {
    "id": "aznar-reciclados-casablanca-nahla-061",
    "name": "Nahla 061",
    "family": "Aznar Casablanca",
    "color": "#C5BEAB",
    "swatch": "/images/fabrics/aznar-reciclados/casablanca-nahla-061.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=6942cec98baf6_1765985993&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Casablanca",
    "fabricType": "Reciclados",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-reciclados-casablanca-daya-061",
    "name": "Daya 061",
    "family": "Aznar Casablanca",
    "color": "#C4BBA6",
    "swatch": "/images/fabrics/aznar-reciclados/casablanca-daya-061.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=6942cec98baf6_1765985993&category=reciclados",
    "manufacturer": "Aznar Textil",
    "collection": "Casablanca",
    "fabricType": "Reciclados",
    "pattern": "Liso"
  }
]

export const AZNAR_RECICLADOS_FABRIC_COUNT = AZNAR_RECICLADOS_FABRICS.length
