export const AZNAR_OUTDOOR_FABRICS = [
  {
    "id": "aznar-outdoor-uni4out-000",
    "name": "Uni4out 000",
    "family": "Aznar Outdoor",
    "color": "#DFDBDF",
    "swatch": "/images/fabrics/aznar-outdoor/uni4out-000.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694032a23c33c_1765814946&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Liso"
  },
  {
    "id": "aznar-outdoor-uni4out-006",
    "name": "Uni4out 006",
    "family": "Aznar Outdoor",
    "color": "#88898C",
    "swatch": "/images/fabrics/aznar-outdoor/uni4out-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694032a23c33c_1765814946&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Liso"
  },
  {
    "id": "aznar-outdoor-uni4out-007",
    "name": "Uni4out 007",
    "family": "Aznar Outdoor",
    "color": "#4D504D",
    "swatch": "/images/fabrics/aznar-outdoor/uni4out-007.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694032a23c33c_1765814946&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Liso"
  },
  {
    "id": "aznar-outdoor-uni4out-009",
    "name": "Uni4out 009",
    "family": "Aznar Outdoor",
    "color": "#302D31",
    "swatch": "/images/fabrics/aznar-outdoor/uni4out-009.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694032a23c33c_1765814946&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Liso"
  },
  {
    "id": "aznar-outdoor-uni4out-020",
    "name": "Uni4out 020",
    "family": "Aznar Outdoor",
    "color": "#2CA3C9",
    "swatch": "/images/fabrics/aznar-outdoor/uni4out-020.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694032a23c33c_1765814946&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Liso"
  },
  {
    "id": "aznar-outdoor-uni4out-021",
    "name": "Uni4out 021",
    "family": "Aznar Outdoor",
    "color": "#012B7B",
    "swatch": "/images/fabrics/aznar-outdoor/uni4out-021.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694032a23c33c_1765814946&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Liso"
  },
  {
    "id": "aznar-outdoor-uni4out-022",
    "name": "Uni4out 022",
    "family": "Aznar Outdoor",
    "color": "#272E48",
    "swatch": "/images/fabrics/aznar-outdoor/uni4out-022.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694032a23c33c_1765814946&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Liso"
  },
  {
    "id": "aznar-outdoor-uni4out-040",
    "name": "Uni4out 040",
    "family": "Aznar Outdoor",
    "color": "#9E0D12",
    "swatch": "/images/fabrics/aznar-outdoor/uni4out-040.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694032a23c33c_1765814946&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Liso"
  },
  {
    "id": "aznar-outdoor-uni4out-063",
    "name": "Uni4out 063",
    "family": "Aznar Outdoor",
    "color": "#A18A61",
    "swatch": "/images/fabrics/aznar-outdoor/uni4out-063.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694032a23c33c_1765814946&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Liso"
  },
  {
    "id": "aznar-outdoor-uni4out-064",
    "name": "Uni4out 064",
    "family": "Aznar Outdoor",
    "color": "#A29A88",
    "swatch": "/images/fabrics/aznar-outdoor/uni4out-064.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694032a23c33c_1765814946&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Liso"
  },
  {
    "id": "aznar-outdoor-uni4out-067",
    "name": "Uni4out 067",
    "family": "Aznar Outdoor",
    "color": "#777168",
    "swatch": "/images/fabrics/aznar-outdoor/uni4out-067.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694032a23c33c_1765814946&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Liso"
  },
  {
    "id": "aznar-outdoor-uni4out-070",
    "name": "Uni4out 070",
    "family": "Aznar Outdoor",
    "color": "#E0A10A",
    "swatch": "/images/fabrics/aznar-outdoor/uni4out-070.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694032a23c33c_1765814946&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Liso"
  },
  {
    "id": "aznar-outdoor-uni4out-075",
    "name": "Uni4out 075",
    "family": "Aznar Outdoor",
    "color": "#CF5803",
    "swatch": "/images/fabrics/aznar-outdoor/uni4out-075.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694032a23c33c_1765814946&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Liso"
  },
  {
    "id": "aznar-outdoor-uni4out-081",
    "name": "Uni4out 081",
    "family": "Aznar Outdoor",
    "color": "#7DA44B",
    "swatch": "/images/fabrics/aznar-outdoor/uni4out-081.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694032a23c33c_1765814946&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Liso"
  },
  {
    "id": "aznar-outdoor-uni4out-082",
    "name": "Uni4out 082",
    "family": "Aznar Outdoor",
    "color": "#005940",
    "swatch": "/images/fabrics/aznar-outdoor/uni4out-082.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694032a23c33c_1765814946&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Liso"
  },
  {
    "id": "aznar-outdoor-stripe4out-006",
    "name": "Stripe4out 006",
    "family": "Aznar Outdoor",
    "color": "#BBBBBE",
    "swatch": "/images/fabrics/aznar-outdoor/stripe4out-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69403423bae59_1765815331&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Rayas"
  },
  {
    "id": "aznar-outdoor-stripe4out-007",
    "name": "Stripe4out 007",
    "family": "Aznar Outdoor",
    "color": "#9C9C9B",
    "swatch": "/images/fabrics/aznar-outdoor/stripe4out-007.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69403423bae59_1765815331&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Rayas"
  },
  {
    "id": "aznar-outdoor-stripe4out-009",
    "name": "Stripe4out 009",
    "family": "Aznar Outdoor",
    "color": "#8C8B8E",
    "swatch": "/images/fabrics/aznar-outdoor/stripe4out-009.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69403423bae59_1765815331&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Rayas"
  },
  {
    "id": "aznar-outdoor-stripe4out-020",
    "name": "Stripe4out 020",
    "family": "Aznar Outdoor",
    "color": "#8BC6D9",
    "swatch": "/images/fabrics/aznar-outdoor/stripe4out-020.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69403423bae59_1765815331&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Rayas"
  },
  {
    "id": "aznar-outdoor-stripe4out-021",
    "name": "Stripe4out 021",
    "family": "Aznar Outdoor",
    "color": "#758AB2",
    "swatch": "/images/fabrics/aznar-outdoor/stripe4out-021.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69403423bae59_1765815331&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Rayas"
  },
  {
    "id": "aznar-outdoor-stripe4out-022",
    "name": "Stripe4out 022",
    "family": "Aznar Outdoor",
    "color": "#898C99",
    "swatch": "/images/fabrics/aznar-outdoor/stripe4out-022.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69403423bae59_1765815331&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Rayas"
  },
  {
    "id": "aznar-outdoor-stripe4out-040",
    "name": "Stripe4out 040",
    "family": "Aznar Outdoor",
    "color": "#C47B7D",
    "swatch": "/images/fabrics/aznar-outdoor/stripe4out-040.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69403423bae59_1765815331&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Rayas"
  },
  {
    "id": "aznar-outdoor-stripe4out-063",
    "name": "Stripe4out 063",
    "family": "Aznar Outdoor",
    "color": "#C5BAA5",
    "swatch": "/images/fabrics/aznar-outdoor/stripe4out-063.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69403423bae59_1765815331&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Rayas"
  },
  {
    "id": "aznar-outdoor-stripe4out-064",
    "name": "Stripe4out 064",
    "family": "Aznar Outdoor",
    "color": "#C7C3BA",
    "swatch": "/images/fabrics/aznar-outdoor/stripe4out-064.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69403423bae59_1765815331&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Rayas"
  },
  {
    "id": "aznar-outdoor-stripe4out-067",
    "name": "Stripe4out 067",
    "family": "Aznar Outdoor",
    "color": "#B0ADA9",
    "swatch": "/images/fabrics/aznar-outdoor/stripe4out-067.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69403423bae59_1765815331&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Rayas"
  },
  {
    "id": "aznar-outdoor-stripe4out-070",
    "name": "Stripe4out 070",
    "family": "Aznar Outdoor",
    "color": "#E5C57A",
    "swatch": "/images/fabrics/aznar-outdoor/stripe4out-070.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69403423bae59_1765815331&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Rayas"
  },
  {
    "id": "aznar-outdoor-stripe4out-075",
    "name": "Stripe4out 075",
    "family": "Aznar Outdoor",
    "color": "#DCA176",
    "swatch": "/images/fabrics/aznar-outdoor/stripe4out-075.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69403423bae59_1765815331&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Rayas"
  },
  {
    "id": "aznar-outdoor-stripe4out-081",
    "name": "Stripe4out 081",
    "family": "Aznar Outdoor",
    "color": "#B3C69A",
    "swatch": "/images/fabrics/aznar-outdoor/stripe4out-081.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69403423bae59_1765815331&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Rayas"
  },
  {
    "id": "aznar-outdoor-stripe4out-082",
    "name": "Stripe4out 082",
    "family": "Aznar Outdoor",
    "color": "#75A195",
    "swatch": "/images/fabrics/aznar-outdoor/stripe4out-082.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69403423bae59_1765815331&category=outdoor",
    "manufacturer": "Aznar Textil",
    "collection": "Outdoor",
    "fabricType": "Outdoor",
    "pattern": "Rayas"
  }
]

export const AZNAR_OUTDOOR_FABRIC_COUNT = AZNAR_OUTDOOR_FABRICS.length
