export const AZNAR_JACQUARD_FABRICS = [
  {
    "id": "aznar-jacquard-batz-006",
    "name": "Batz 006",
    "family": "Aznar Les Marins",
    "color": "#969799",
    "swatch": "/images/fabrics/aznar-jacquard/les-marins-batz-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=6931502155f8f_1764839457&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Les Marins",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-marcel-006",
    "name": "Marcel 006",
    "family": "Aznar Les Marins",
    "color": "#B1B3B1",
    "swatch": "/images/fabrics/aznar-jacquard/les-marins-marcel-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=6931502155f8f_1764839457&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Les Marins",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-michel-006",
    "name": "Michel 006",
    "family": "Aznar Les Marins",
    "color": "#C6C8C5",
    "swatch": "/images/fabrics/aznar-jacquard/les-marins-michel-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=6931502155f8f_1764839457&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Les Marins",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-james-006",
    "name": "James 006",
    "family": "Aznar Les Marins",
    "color": "#C3C5C2",
    "swatch": "/images/fabrics/aznar-jacquard/les-marins-james-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=6931502155f8f_1764839457&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Les Marins",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-michel-061",
    "name": "Michel 061",
    "family": "Aznar Les Marins",
    "color": "#EFEEE9",
    "swatch": "/images/fabrics/aznar-jacquard/les-marins-michel-061.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69315c604982d_1764842592&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Les Marins",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-batz-061",
    "name": "Batz 061",
    "family": "Aznar Les Marins",
    "color": "#D2CEBD",
    "swatch": "/images/fabrics/aznar-jacquard/les-marins-batz-061.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69315c604982d_1764842592&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Les Marins",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-marcel-061",
    "name": "Marcel 061",
    "family": "Aznar Les Marins",
    "color": "#DCD8CD",
    "swatch": "/images/fabrics/aznar-jacquard/les-marins-marcel-061.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69315c604982d_1764842592&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Les Marins",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-james-061",
    "name": "James 061",
    "family": "Aznar Les Marins",
    "color": "#F0EFEA",
    "swatch": "/images/fabrics/aznar-jacquard/les-marins-james-061.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69315c604982d_1764842592&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Les Marins",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-000",
    "name": "000",
    "family": "Aznar Pike",
    "color": "#E7E7E5",
    "swatch": "/images/fabrics/aznar-jacquard/pike-000.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=693bf2fbd670f_1765536507&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Pike",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-061",
    "name": "061",
    "family": "Aznar Pike",
    "color": "#E1DECD",
    "swatch": "/images/fabrics/aznar-jacquard/pike-061.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=693bf2fbd670f_1765536507&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Pike",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-adriana-006",
    "name": "Adriana 006",
    "family": "Aznar Domus",
    "color": "#B2B5B3",
    "swatch": "/images/fabrics/aznar-jacquard/domus-adriana-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-adriana-030",
    "name": "Adriana 030",
    "family": "Aznar Domus",
    "color": "#EFEEE1",
    "swatch": "/images/fabrics/aznar-jacquard/domus-adriana-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-diana-006",
    "name": "Diana 006",
    "family": "Aznar Domus",
    "color": "#BBBDBF",
    "swatch": "/images/fabrics/aznar-jacquard/domus-diana-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-diana-030",
    "name": "Diana 030",
    "family": "Aznar Domus",
    "color": "#C9C5BB",
    "swatch": "/images/fabrics/aznar-jacquard/domus-diana-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-fannia-006",
    "name": "Fannia 006",
    "family": "Aznar Domus",
    "color": "#B1B3B5",
    "swatch": "/images/fabrics/aznar-jacquard/domus-fannia-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-fannia-030",
    "name": "Fannia 030",
    "family": "Aznar Domus",
    "color": "#D3CFC4",
    "swatch": "/images/fabrics/aznar-jacquard/domus-fannia-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-hora-006",
    "name": "Hora 006",
    "family": "Aznar Domus",
    "color": "#B6B8B7",
    "swatch": "/images/fabrics/aznar-jacquard/domus-hora-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-hora-030",
    "name": "Hora 030",
    "family": "Aznar Domus",
    "color": "#EFEDE2",
    "swatch": "/images/fabrics/aznar-jacquard/domus-hora-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-iris-006",
    "name": "Iris 006",
    "family": "Aznar Domus",
    "color": "#AFB1B0",
    "swatch": "/images/fabrics/aznar-jacquard/domus-iris-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-iris-030",
    "name": "Iris 030",
    "family": "Aznar Domus",
    "color": "#ECEADE",
    "swatch": "/images/fabrics/aznar-jacquard/domus-iris-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-juno-006",
    "name": "Juno 006",
    "family": "Aznar Domus",
    "color": "#B5B7B7",
    "swatch": "/images/fabrics/aznar-jacquard/domus-juno-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-juno-030",
    "name": "Juno 030",
    "family": "Aznar Domus",
    "color": "#ECEBE0",
    "swatch": "/images/fabrics/aznar-jacquard/domus-juno-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-malena-006",
    "name": "Malena 006",
    "family": "Aznar Domus",
    "color": "#B6B8B7",
    "swatch": "/images/fabrics/aznar-jacquard/domus-malena-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-malena-030",
    "name": "Malena 030",
    "family": "Aznar Domus",
    "color": "#EEECE1",
    "swatch": "/images/fabrics/aznar-jacquard/domus-malena-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-marcia-006",
    "name": "Marcia 006",
    "family": "Aznar Domus",
    "color": "#B2B4B6",
    "swatch": "/images/fabrics/aznar-jacquard/domus-marcia-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-marcia-030",
    "name": "Marcia 030",
    "family": "Aznar Domus",
    "color": "#C9C5BB",
    "swatch": "/images/fabrics/aznar-jacquard/domus-marcia-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-tulia-006",
    "name": "Tulia 006",
    "family": "Aznar Domus",
    "color": "#BFC1C2",
    "swatch": "/images/fabrics/aznar-jacquard/domus-tulia-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-tulia-030",
    "name": "Tulia 030",
    "family": "Aznar Domus",
    "color": "#C9C5BB",
    "swatch": "/images/fabrics/aznar-jacquard/domus-tulia-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-velia-006",
    "name": "Velia 006",
    "family": "Aznar Domus",
    "color": "#C0C2C4",
    "swatch": "/images/fabrics/aznar-jacquard/domus-velia-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-velia-030",
    "name": "Velia 030",
    "family": "Aznar Domus",
    "color": "#C9C5BB",
    "swatch": "/images/fabrics/aznar-jacquard/domus-velia-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69413bddf208b_1765882845&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-seya-006",
    "name": "Seya 006",
    "family": "Aznar Domus",
    "color": "#B0B2B4",
    "swatch": "/images/fabrics/aznar-jacquard/domus-seya-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694141cd4c561_1765884365&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-seya-030",
    "name": "Seya 030",
    "family": "Aznar Domus",
    "color": "#D4D0C5",
    "swatch": "/images/fabrics/aznar-jacquard/domus-seya-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=694141cd4c561_1765884365&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-elia-006",
    "name": "Elia 006",
    "family": "Aznar Domus",
    "color": "#B4B6B7",
    "swatch": "/images/fabrics/aznar-jacquard/domus-elia-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69414797b051d_1765885847&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-elia-030",
    "name": "Elia 030",
    "family": "Aznar Domus",
    "color": "#D5D0C5",
    "swatch": "/images/fabrics/aznar-jacquard/domus-elia-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69414797b051d_1765885847&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-helena-006",
    "name": "Helena 006",
    "family": "Aznar Domus",
    "color": "#B6B7BA",
    "swatch": "/images/fabrics/aznar-jacquard/domus-helena-006.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69415478d2c97_1765889144&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  },
  {
    "id": "aznar-jacquard-helena-030",
    "name": "Helena 030",
    "family": "Aznar Domus",
    "color": "#D6D0C5",
    "swatch": "/images/fabrics/aznar-jacquard/domus-helena-030.webp",
    "article": "https://www.bondrap.com/php/view-product.php?id=69415478d2c97_1765889144&category=jacquard",
    "manufacturer": "Aznar Textil",
    "collection": "Domus",
    "fabricType": "Jacquard",
    "pattern": "Geometricos"
  }
]

export const AZNAR_JACQUARD_FABRIC_COUNT = AZNAR_JACQUARD_FABRICS.length
