export const FROCA_FABRICS = [
  {
    id: 'acanto-01',
    name: 'ACANTO 01',
    family: 'Froca Acanto',
    color: '#060606',
    swatch: '/images/fabrics/acanto/acanto-01.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-02',
    name: 'ACANTO 02',
    family: 'Froca Acanto',
    color: '#1B1B1B',
    swatch: '/images/fabrics/acanto/acanto-02.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-03',
    name: 'ACANTO 03',
    family: 'Froca Acanto',
    color: '#303030',
    swatch: '/images/fabrics/acanto/acanto-03.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-04',
    name: 'ACANTO 04',
    family: 'Froca Acanto',
    color: '#6D6963',
    swatch: '/images/fabrics/acanto/acanto-04.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-05',
    name: 'ACANTO 05',
    family: 'Froca Acanto',
    color: '#938D8B',
    swatch: '/images/fabrics/acanto/acanto-05.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-06',
    name: 'ACANTO 06',
    family: 'Froca Acanto',
    color: '#909090',
    swatch: '/images/fabrics/acanto/acanto-06.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-07',
    name: 'ACANTO 07',
    family: 'Froca Acanto',
    color: '#9A948F',
    swatch: '/images/fabrics/acanto/acanto-07.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-08',
    name: 'ACANTO 08',
    family: 'Froca Acanto',
    color: '#DDDAD1',
    swatch: '/images/fabrics/acanto/acanto-08.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-09',
    name: 'ACANTO 09',
    family: 'Froca Acanto',
    color: '#C5C1B6',
    swatch: '/images/fabrics/acanto/acanto-09.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-10',
    name: 'ACANTO 10',
    family: 'Froca Acanto',
    color: '#BEB39B',
    swatch: '/images/fabrics/acanto/acanto-10.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-11',
    name: 'ACANTO 11',
    family: 'Froca Acanto',
    color: '#9F9584',
    swatch: '/images/fabrics/acanto/acanto-11.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-12',
    name: 'ACANTO 12',
    family: 'Froca Acanto',
    color: '#8E8A7E',
    swatch: '/images/fabrics/acanto/acanto-12.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-13',
    name: 'ACANTO 13',
    family: 'Froca Acanto',
    color: '#665D58',
    swatch: '/images/fabrics/acanto/acanto-13.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-14',
    name: 'ACANTO 14',
    family: 'Froca Acanto',
    color: '#41372F',
    swatch: '/images/fabrics/acanto/acanto-14.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-15',
    name: 'ACANTO 15',
    family: 'Froca Acanto',
    color: '#A38132',
    swatch: '/images/fabrics/acanto/acanto-15.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-16',
    name: 'ACANTO 16',
    family: 'Froca Acanto',
    color: '#5D4528',
    swatch: '/images/fabrics/acanto/acanto-16.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-17',
    name: 'ACANTO 17',
    family: 'Froca Acanto',
    color: '#A19270',
    swatch: '/images/fabrics/acanto/acanto-17.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-18',
    name: 'ACANTO 18',
    family: 'Froca Acanto',
    color: '#9C643B',
    swatch: '/images/fabrics/acanto/acanto-18.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-19',
    name: 'ACANTO 19',
    family: 'Froca Acanto',
    color: '#703323',
    swatch: '/images/fabrics/acanto/acanto-19.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-20',
    name: 'ACANTO 20',
    family: 'Froca Acanto',
    color: '#4A1B19',
    swatch: '/images/fabrics/acanto/acanto-20.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-21',
    name: 'ACANTO 21',
    family: 'Froca Acanto',
    color: '#562326',
    swatch: '/images/fabrics/acanto/acanto-21.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-22',
    name: 'ACANTO 22',
    family: 'Froca Acanto',
    color: '#9B615E',
    swatch: '/images/fabrics/acanto/acanto-22.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-23',
    name: 'ACANTO 23',
    family: 'Froca Acanto',
    color: '#B89288',
    swatch: '/images/fabrics/acanto/acanto-23.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-24',
    name: 'ACANTO 24',
    family: 'Froca Acanto',
    color: '#1F232D',
    swatch: '/images/fabrics/acanto/acanto-24.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-25',
    name: 'ACANTO 25',
    family: 'Froca Acanto',
    color: '#192648',
    swatch: '/images/fabrics/acanto/acanto-25.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-26',
    name: 'ACANTO 26',
    family: 'Froca Acanto',
    color: '#19696E',
    swatch: '/images/fabrics/acanto/acanto-26.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-27',
    name: 'ACANTO 27',
    family: 'Froca Acanto',
    color: '#576670',
    swatch: '/images/fabrics/acanto/acanto-27.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-28',
    name: 'ACANTO 28',
    family: 'Froca Acanto',
    color: '#AAB5B6',
    swatch: '/images/fabrics/acanto/acanto-28.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-29',
    name: 'ACANTO 29',
    family: 'Froca Acanto',
    color: '#C5B34F',
    swatch: '/images/fabrics/acanto/acanto-29.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-30',
    name: 'ACANTO 30',
    family: 'Froca Acanto',
    color: '#9D913A',
    swatch: '/images/fabrics/acanto/acanto-30.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-31',
    name: 'ACANTO 31',
    family: 'Froca Acanto',
    color: '#83846E',
    swatch: '/images/fabrics/acanto/acanto-31.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-32',
    name: 'ACANTO 32',
    family: 'Froca Acanto',
    color: '#5A645F',
    swatch: '/images/fabrics/acanto/acanto-32.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-33',
    name: 'ACANTO 33',
    family: 'Froca Acanto',
    color: '#464A3D',
    swatch: '/images/fabrics/acanto/acanto-33.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'acanto-34',
    name: 'ACANTO 34',
    family: 'Froca Acanto',
    color: '#2C342D',
    swatch: '/images/fabrics/acanto/acanto-34.webp',
    article: 'https://froca.com/es/art/tapiceria-ACANTO',
  },
  {
    id: 'balenciaga-01',
    name: 'BALENCIAGA 01',
    family: 'Froca Balenciaga',
    color: '#767676',
    swatch: '/images/fabrics/balenciaga/balenciaga-01.webp',
    article: 'https://froca.com/es/art/tapiceria-BALENCIAGA',
  },
  {
    id: 'balenciaga-02',
    name: 'BALENCIAGA 02',
    family: 'Froca Balenciaga',
    color: '#A6A7A3',
    swatch: '/images/fabrics/balenciaga/balenciaga-02.webp',
    article: 'https://froca.com/es/art/tapiceria-BALENCIAGA',
  },
  {
    id: 'balenciaga-03',
    name: 'BALENCIAGA 03',
    family: 'Froca Balenciaga',
    color: '#CABFA6',
    swatch: '/images/fabrics/balenciaga/balenciaga-03.webp',
    article: 'https://froca.com/es/art/tapiceria-BALENCIAGA',
  },
  {
    id: 'balenciaga-04',
    name: 'BALENCIAGA 04',
    family: 'Froca Balenciaga',
    color: '#908D83',
    swatch: '/images/fabrics/balenciaga/balenciaga-04.webp',
    article: 'https://froca.com/es/art/tapiceria-BALENCIAGA',
  },
  {
    id: 'balenciaga-05',
    name: 'BALENCIAGA 05',
    family: 'Froca Balenciaga',
    color: '#8E7E5A',
    swatch: '/images/fabrics/balenciaga/balenciaga-05.webp',
    article: 'https://froca.com/es/art/tapiceria-BALENCIAGA',
  },
  {
    id: 'balenciaga-06',
    name: 'BALENCIAGA 06',
    family: 'Froca Balenciaga',
    color: '#727A7A',
    swatch: '/images/fabrics/balenciaga/balenciaga-06.webp',
    article: 'https://froca.com/es/art/tapiceria-BALENCIAGA',
  },
  {
    id: 'balenciaga-07',
    name: 'BALENCIAGA 07',
    family: 'Froca Balenciaga',
    color: '#636363',
    swatch: '/images/fabrics/balenciaga/balenciaga-07.webp',
    article: 'https://froca.com/es/art/tapiceria-BALENCIAGA',
  },
  {
    id: 'balenciaga-08',
    name: 'BALENCIAGA 08',
    family: 'Froca Balenciaga',
    color: '#8C9383',
    swatch: '/images/fabrics/balenciaga/balenciaga-08.webp',
    article: 'https://froca.com/es/art/tapiceria-BALENCIAGA',
  },
]

export const FROCA_FABRIC_COUNTS = {
  acanto: FROCA_FABRICS.filter((item) => item.id.startsWith('acanto-')).length,
  balenciaga: FROCA_FABRICS.filter((item) => item.id.startsWith('balenciaga-')).length,
}
